services:
  capstone-backend:
    image: python:3.12-slim
    container_name: capstone-backend
    volumes:
      - .:/app
      - hf_cache:/root/.cache/huggingface
    working_dir: /app
    command: >
      sh -c "apt-get update && 
             apt-get install -y libgomp1 procps curl net-tools && 
             tail -f /dev/null"
    tty: true
    stdin_open: true
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8888:8888"
    environment:
      - TZ=Asia/Jakarta
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - capstone-network

volumes:
  hf_cache:

networks:
  capstone-network:
    external: true