services:
  casptone-backend:
    container_name: capstone-backend
    build: .
    volumes:
      - .:/app
    working_dir: /app
    tty: true        
    stdin_open: true
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Jakarta

    networks:
      - capstone-network
      
networks:
  capstone-network:
    external: true
